### ISSUE TITLE
ISO C++ forbid

### ISSUE THREAD

**Issue by zero-voyager** [hans-robot/elfin_robot_ros2#3]
好家伙，我在Ubuntu22的ros2-humble下面编译，Ethercat包好多ISO C forbids，有大佬有解决方案吗

**Comment by Neverforgetlove** [comment]
一些警告，不影响

**Comment by Neverforgetlove** [comment]
> 好家伙，我在Ubuntu22的ros2-humble下面编译，Ethercat包好多ISO C forbids，有大佬有解决方案吗

一些警告，不影响

**Comment by zero-voyager** [comment]
换个soem版本，就行
